[project]
name = "WES-iGPA-Calculator-AutoEntry"
version = "0.1.0"
description = "WES iGPA Calculator Auto-Entry"
readme = "README.md"
dependencies = [
    "pandas",
    "selenium",
]
requires-python = ">=3.12"
